# Generated by Django 5.0 on 2023-12-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=150, unique=True, verbose_name="электронная почта"
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="пароль")),
                (
                    "phone",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="номер телефона"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="user", verbose_name="аватар"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        default="user",
                        max_length=30,
                        verbose_name="Роль",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
